### ISSUE TITLE
Add open source license for PicoLA

### ISSUE THREAD

**Issue by yungyuc** [OscarShiang/PicoLA#1]
@OscarShiang , please add an open source license for your project. If you are not sure how to do it, see https://github.com/solvcon/modmesh.

**Comment by yungyuc** [comment]
@OscarShiang any update?

The repository is still empty.  According to [your schedule](https://github.com/yungyuc/nsdhw_24au/blob/ed6f48bf0412b8a5f9324cd055c49a4906700e8c/project/OscarShiang/README.rst?plain=1#L99), there should be Github Actions set up by now.  Please update your progress.

**Comment by OscarShiang** [comment]
Sorry for the delayed response.

I have added a license file at #2.

**Comment by OscarShiang** [comment]
Out of curiosity, should we add the license statement to each source file?

**Comment by yungyuc** [comment]
> Sorry for the delayed response.
> 
> I have added a license file at #2.

This is your project.  Merge as you want.

If you would like to have my review, leave a comment in the PR tagging me.

But for a simple request like this, you just go ahead.  I don't think any review is necessary.

> Out of curiosity, should we add the license statement to each source file?

Good question.  It depends.  Either way is OK and has different implications.

**Comment by OscarShiang** [comment]
This issue has be solved by #2.
